using Npgsql;

namespace Characterdle.Server.Features.Leaderboard;

public sealed class LeaderboardSchemaInitializer(
    NpgsqlDataSource dataSource,
    ILogger<LeaderboardSchemaInitializer> logger)
{
    private const string SchemaSql =
        """
        create table if not exists public."PlayerProfiles" (
          user_id uuid primary key references auth.users(id) on delete cascade,
          display_name text not null,
          email text not null,
          avatar_url text null,
          created_at timestamptz not null default timezone('utc', now()),
          updated_at timestamptz not null default timezone('utc', now())
        );

        create table if not exists public."UniverseGameResults" (
          id bigint generated by default as identity primary key,
          user_id uuid not null references public."PlayerProfiles"(user_id) on delete cascade,
          universe_id text not null,
          game_id bigint not null,
          mode text not null default 'character',
          status text not null,
          guess_count integer not null,
          hint_count integer not null,
          completed_at timestamptz not null default timezone('utc', now()),
          constraint universe_game_results_mode_check check (mode in ('character', 'quote')),
          constraint universe_game_results_status_check check (status in ('won', 'lost')),
          constraint universe_game_results_guess_count_check check (guess_count >= 0),
          constraint universe_game_results_hint_count_check check (hint_count >= 0),
          constraint universe_game_results_unique unique (user_id, universe_id, game_id, mode)
        );

        alter table public."UniverseGameResults"
          add column if not exists mode text not null default 'character';

        update public."UniverseGameResults"
        set mode = 'character'
        where mode is null;

        alter table public."UniverseGameResults"
          drop constraint if exists universe_game_results_unique;

        do $$
        begin
          if not exists (
            select 1
            from pg_constraint
            where conname = 'universe_game_results_mode_check'
          ) then
            alter table public."UniverseGameResults"
              add constraint universe_game_results_mode_check
              check (mode in ('character', 'quote'));
          end if;
        end
        $$;

        create unique index if not exists idx_universe_game_results_unique_round
          on public."UniverseGameResults" (user_id, universe_id, game_id, mode);

        create index if not exists idx_universe_game_results_universe
          on public."UniverseGameResults" (universe_id, mode, status, completed_at desc);

        create index if not exists idx_universe_game_results_user
          on public."UniverseGameResults" (user_id, universe_id, mode);
        """;

    public async Task EnsureInitializedAsync(CancellationToken cancellationToken = default)
    {
        await using var command = dataSource.CreateCommand(SchemaSql);
        await command.ExecuteNonQueryAsync(cancellationToken);
        logger.LogInformation("Leaderboard schema is ready.");
    }
}
