namespace Characterdle.Server.Infrastructure.Database;

public sealed class Migration002CreateGotQuotesSchema : IDatabaseMigration
{
    public string Description => "Create and normalize Game of Thrones quote storage and quote-to-game links.";

    public string Id => "002_create_got_quotes_schema";

    public string Sql =>
        """
        create table if not exists public."GOTQuotes" (
          id bigint generated by default as identity primary key,
          character_id bigint not null references public."GOTCharacters"(id) on delete cascade,
          quote_text text not null,
          season_number integer not null,
          episode_number integer not null
        );

        alter table public."GOTGames"
          add column if not exists quote_id bigint;

        do $$
        begin
          if not exists (
            select 1
            from pg_constraint
            where conname = 'gotgames_quote_id_fkey'
          ) then
            alter table public."GOTGames"
              add constraint gotgames_quote_id_fkey
              foreign key (quote_id) references public."GOTQuotes"(id)
              on delete set null;
          end if;
        end
        $$;

        create unique index if not exists idx_gotquotes_character_text
          on public."GOTQuotes" (character_id, quote_text);

        create index if not exists idx_gotquotes_character_id
          on public."GOTQuotes" (character_id);

        create index if not exists idx_gotgames_quote_id
          on public."GOTGames" (quote_id);

        with quote_pool as (
          select
            quotes.id,
            row_number() over (order by quotes.id) - 1 as quote_position
          from public."GOTQuotes" as quotes
        ),
        quote_count as (
          select count(*)::bigint as total
          from quote_pool
        ),
        ranked_games as (
          select
            games.id,
            row_number() over (order by games.datetime, games.id) - 1 as game_position
          from public."GOTGames" as games
          where games.quote_id is null
        )
        update public."GOTGames" as games
        set quote_id = quote_pool.id
        from ranked_games, quote_count, quote_pool
        where games.id = ranked_games.id
          and quote_count.total > 0
          and quote_pool.quote_position = mod(ranked_games.game_position, quote_count.total);
        """;
}
