namespace Characterdle.Server.Infrastructure.Database;

public sealed class Migration001CreateGotCoreSchema : IDatabaseMigration
{
    public string Description => "Create and normalize the core Game of Thrones character and game tables.";

    public string Id => "001_create_got_core_schema";

    public string Sql =>
        """
        create table if not exists public."GOTCharacters" (
          id bigint generated by default as identity primary key,
          display_name text not null,
          aliases text[] not null default '{}'::text[],
          portrait_url text null,
          gender text not null default 'ERROR',
          species text not null default 'ERROR',
          house text[] not null default array['Lowborn']::text[],
          occupation text[] not null default '{}'::text[],
          debut_season integer not null default 0,
          last_season integer not null default 0,
          alive boolean not null default false
        );

        alter table public."GOTCharacters"
          add column if not exists display_name text;

        alter table public."GOTCharacters"
          add column if not exists aliases text[] default '{}'::text[];

        alter table public."GOTCharacters"
          add column if not exists portrait_url text;

        alter table public."GOTCharacters"
          add column if not exists gender text default 'ERROR';

        alter table public."GOTCharacters"
          add column if not exists species text default 'ERROR';

        alter table public."GOTCharacters"
          add column if not exists house text[] default array['Lowborn']::text[];

        alter table public."GOTCharacters"
          add column if not exists occupation text[] default '{}'::text[];

        alter table public."GOTCharacters"
          add column if not exists debut_season integer default 0;

        alter table public."GOTCharacters"
          add column if not exists last_season integer default 0;

        alter table public."GOTCharacters"
          add column if not exists alive boolean default false;

        update public."GOTCharacters"
        set
          display_name = coalesce(nullif(trim(display_name), ''), 'ERROR'),
          aliases = coalesce(aliases, '{}'::text[]),
          gender = coalesce(nullif(trim(gender), ''), 'ERROR'),
          species = coalesce(nullif(trim(species), ''), 'ERROR'),
          house = coalesce(house, array['Lowborn']::text[]),
          occupation = coalesce(occupation, '{}'::text[]),
          debut_season = coalesce(debut_season, 0),
          last_season = coalesce(last_season, 0),
          alive = coalesce(alive, false);

        alter table public."GOTCharacters"
          alter column display_name set not null;

        alter table public."GOTCharacters"
          alter column aliases set default '{}'::text[];

        alter table public."GOTCharacters"
          alter column aliases set not null;

        alter table public."GOTCharacters"
          alter column gender set default 'ERROR';

        alter table public."GOTCharacters"
          alter column gender set not null;

        alter table public."GOTCharacters"
          alter column species set default 'ERROR';

        alter table public."GOTCharacters"
          alter column species set not null;

        alter table public."GOTCharacters"
          alter column house set default array['Lowborn']::text[];

        alter table public."GOTCharacters"
          alter column house set not null;

        alter table public."GOTCharacters"
          alter column occupation set default '{}'::text[];

        alter table public."GOTCharacters"
          alter column occupation set not null;

        alter table public."GOTCharacters"
          alter column debut_season set default 0;

        alter table public."GOTCharacters"
          alter column debut_season set not null;

        alter table public."GOTCharacters"
          alter column last_season set default 0;

        alter table public."GOTCharacters"
          alter column last_season set not null;

        alter table public."GOTCharacters"
          alter column alive set default false;

        alter table public."GOTCharacters"
          alter column alive set not null;

        create table if not exists public."GOTGames" (
          id bigint generated by default as identity primary key,
          datetime timestamptz not null,
          character_id bigint not null references public."GOTCharacters"(id) on delete restrict
        );

        alter table public."GOTGames"
          add column if not exists datetime timestamptz;

        alter table public."GOTGames"
          add column if not exists character_id bigint;

        do $$
        begin
          if not exists (
            select 1
            from pg_constraint
            where conname = 'gotgames_character_id_fkey'
          ) then
            alter table public."GOTGames"
              add constraint gotgames_character_id_fkey
              foreign key (character_id) references public."GOTCharacters"(id)
              on delete restrict;
          end if;
        end
        $$;

        create index if not exists idx_gotcharacters_display_name
          on public."GOTCharacters" (lower(display_name));

        create index if not exists idx_gotgames_datetime_desc
          on public."GOTGames" (datetime desc);

        create unique index if not exists idx_gotgames_datetime_unique
          on public."GOTGames" (datetime);

        create index if not exists idx_gotgames_character_id
          on public."GOTGames" (character_id);
        """;
}
