// Maintenance only: builds use the checked-in assets and never contact Google Fonts.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';

const fonts = new URL('../src/assets/fonts/', import.meta.url);
const licenses = new URL('../public/licenses/', import.meta.url);
const stylesheet = 'https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700&family=Cormorant+Garamond:wght@500;600;700&family=Inter:wght@400;500;600;700;800&display=swap';
const families = {
  Cinzel: { slug: 'cinzel', weights: '600 700', upstream: 'cinzel' },
  'Cormorant Garamond': { slug: 'cormorant-garamond', weights: '500 700', upstream: 'cormorantgaramond' },
  Inter: { slug: 'inter', weights: '400 800', upstream: 'inter' },
};

async function download(url) {
  const response = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36' },
  });
  if (!response.ok) throw new Error(`${response.status}: ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

await mkdir(fonts, { recursive: true });
await mkdir(licenses, { recursive: true });
const css = (await download(stylesheet)).toString('utf8');
const faces = new Map();
for (const match of css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face\s*\{([^}]+)\}/g)) {
  const [, subset, face] = match;
  const family = /font-family: '([^']+)'/.exec(face)?.[1];
  const definition = families[family];
  assert.ok(definition, `Unexpected family: ${family}`);
  const source = /src: url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/.exec(face)?.[1];
  const range = /unicode-range: ([^;]+);/.exec(face)?.[1];
  assert.ok(source && range, `Expected WOFF2 and unicode-range for ${family}`);
  const filename = `${definition.slug}-${subset}.woff2`;
  if (faces.has(filename)) {
    assert.equal(faces.get(filename).source, source, 'Weights must share the same variable font.');
    continue;
  }
  const bytes = await download(source);
  assert.equal(bytes.subarray(0, 4).toString(), 'wOF2');
  await writeFile(new URL(filename, fonts), bytes);
  faces.set(filename, { family, subset, source, filename, weights: definition.weights, range,
    bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') });
}
assert.equal(faces.size, 14, 'Review changed upstream subset coverage before updating.');

const declarations = [...faces.values()].map(font => `/* ${font.subset} */
@font-face {
  font-family: '${font.family}';
  font-style: normal;
  font-weight: ${font.weights};
  font-display: swap;
  src: url('./${font.filename}') format('woff2');
  unicode-range: ${font.range};
}`).join('\n\n');
await writeFile(new URL('fonts.css', fonts), `/* Generated by scripts/vendor-fonts.mjs; preserve the existing weight limits. */\n${declarations}\n`);
await writeFile(new URL('sources.json', fonts), `${JSON.stringify({ stylesheet, fonts: [...faces.values()] }, null, 2)}\n`);

for (const { slug, upstream } of Object.values(families)) {
  const license = await download(`https://raw.githubusercontent.com/google/fonts/main/ofl/${upstream}/OFL.txt`);
  assert.ok(license.toString().includes('SIL OPEN FONT LICENSE'));
  await writeFile(new URL(`${slug}-OFL.txt`, licenses), license);
}
const iconLicense = await download('https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE');
assert.ok(iconLicense.toString().includes('Apache License'));
await writeFile(new URL('material-symbols-Apache-2.0.txt', licenses), iconLicense);
console.log(`Vendored ${faces.size} WOFF2 subsets and their licenses.`);
