using Npgsql;

var connectionString = Environment.GetEnvironmentVariable("SUPABASE_CONNECTION_STRING");

if (string.IsNullOrWhiteSpace(connectionString))
{
    throw new InvalidOperationException("SUPABASE_CONNECTION_STRING is required.");
}

var seedFilePath = Path.GetFullPath(
    Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "SeedData", "got-characters.sql"));
var gameSeedFilePath = Path.GetFullPath(
    Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "SeedData", "got-games.sql"));

if (!File.Exists(seedFilePath))
{
    throw new FileNotFoundException("Seed SQL file was not found.", seedFilePath);
}

if (!File.Exists(gameSeedFilePath))
{
    throw new FileNotFoundException("Game seed SQL file was not found.", gameSeedFilePath);
}

var characterSeedSql = await File.ReadAllTextAsync(seedFilePath);
var gameSeedSql = await File.ReadAllTextAsync(gameSeedFilePath);

if (!characterSeedSql.Contains("insert into public.\"GOTCharacters\"", StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException("Seed SQL file does not target public.\"GOTCharacters\".");
}

if (!gameSeedSql.Contains("insert into public.\"GOTGames\"", StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException("Game seed SQL file does not target public.\"GOTGames\".");
}

const string schemaSql =
    """
    create table if not exists public."GOTCharacters" (
      id bigint generated by default as identity primary key,
      display_name text not null unique,
      aliases text[] not null default '{}',
      portrait_url text,
      gender text not null,
      species text not null,
      house text[] not null default '{"Lowborn"}',
      occupation text[] not null default '{}',
      debut_season integer not null,
      last_season integer not null,
      alive boolean not null
    );

    do $$
    begin
      if not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'GOTCharacters'
          and column_name = 'portrait_url'
      ) then
        alter table public."GOTCharacters"
          add column portrait_url text;
      end if;

      if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'GOTCharacters'
          and column_name = 'house'
          and data_type = 'text'
      ) then
        alter table public."GOTCharacters"
          alter column house drop default,
          alter column house type text[]
          using case
            when house is null or btrim(house) = '' then array['Lowborn']::text[]
            else array[house]::text[]
          end,
          alter column house set default '{"Lowborn"}';
      end if;

      if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'GOTCharacters'
          and column_name = 'occupation'
          and data_type = 'text'
      ) then
        alter table public."GOTCharacters"
          alter column occupation drop default,
          alter column occupation type text[]
          using case
            when occupation is null or btrim(occupation) = '' then '{}'::text[]
            else array[occupation]::text[]
          end,
          alter column occupation set default '{}';
      end if;
    end $$;

    create table if not exists public."GOTGames" (
      id bigint generated by default as identity primary key,
      datetime timestamptz not null,
      character_id bigint not null references public."GOTCharacters"(id) on delete cascade
    );

    create index if not exists idx_gotgames_datetime on public."GOTGames" (datetime desc);
    create index if not exists idx_gotgames_character_id on public."GOTGames" (character_id);

    alter table public."GOTCharacters" enable row level security;
    alter table public."GOTGames" enable row level security;

    do $$
    begin
      if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'GOTCharacters'
          and policyname = 'Public read GOTCharacters'
      ) then
        create policy "Public read GOTCharacters"
        on public."GOTCharacters"
        for select
        using (true);
      end if;

      if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'GOTGames'
          and policyname = 'Public read GOTGames'
      ) then
        create policy "Public read GOTGames"
        on public."GOTGames"
        for select
        using (true);
      end if;
    end $$;
    """;

const string replaceDataSql =
    """
    truncate table public."GOTGames" restart identity;
    """;

const string characterCountSql =
    """
    select count(*) from public."GOTCharacters";
    """;

const string verifySql =
    """
    select
      (select count(*) from public."GOTCharacters") as character_count,
      (select count(*) from public."GOTGames") as game_count,
      (
        select characters.display_name
        from public."GOTGames" as games
        join public."GOTCharacters" as characters
          on characters.id = games.character_id
        where games.datetime <= now()
        order by games.datetime desc
        limit 1
      ) as current_answer;
    """;

await using var dataSource = NpgsqlDataSource.Create(connectionString);
await using var connection = await dataSource.OpenConnectionAsync();
await using var transaction = await connection.BeginTransactionAsync();

await ExecuteNonQueryAsync(connection, transaction, schemaSql);
var existingCharacterCount = await ExecuteScalarInt64Async(connection, transaction, characterCountSql);
await ExecuteNonQueryAsync(connection, transaction, replaceDataSql);

if (existingCharacterCount == 0)
{
    await ExecuteNonQueryAsync(connection, transaction, characterSeedSql);
}

await ExecuteNonQueryAsync(connection, transaction, gameSeedSql);

await using var verifyCommand = new NpgsqlCommand(verifySql, connection, transaction);
await using var verifyReader = await verifyCommand.ExecuteReaderAsync();
await verifyReader.ReadAsync();

var characterCount = verifyReader.GetInt64(0);
var gameCount = verifyReader.GetInt64(1);
var currentAnswer = verifyReader.IsDBNull(2) ? "ERROR" : verifyReader.GetString(2);

await verifyReader.CloseAsync();
await transaction.CommitAsync();

Console.WriteLine(
    $"Supabase Game of Thrones data is ready. GOTCharacters={characterCount}, GOTGames={gameCount}, CurrentAnswer={currentAnswer}");

static async Task ExecuteNonQueryAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection, transaction);
    await command.ExecuteNonQueryAsync();
}

static async Task<long> ExecuteScalarInt64Async(NpgsqlConnection connection, NpgsqlTransaction transaction, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection, transaction);
    var result = await command.ExecuteScalarAsync();

    return result switch
    {
        long value => value,
        int value => value,
        _ => throw new InvalidOperationException("Expected an integer scalar result.")
    };
}
